insert into Productos (descripcion, stock, precio) values ('Versatainer Nc - 9388', 55, 6187.96);
insert into Productos (descripcion, stock, precio) values ('Puree - Kiwi', 21, 4207.28);
insert into Productos (descripcion, stock, precio) values ('Dried Peach', 63, 4719.99);
insert into Productos (descripcion, stock, precio) values ('Wine - Acient Coast Caberne', 49, 9800.83);
insert into Productos (descripcion, stock, precio) values ('Beef - Tenderlion, Center Cut', 93, 7411.16);
insert into Productos (descripcion, stock, precio) values ('Cookie - Oatmeal', 86, 2927.11);
insert into Productos (descripcion, stock, precio) values ('Steam Pan - Half Size Deep', 41, 8525.23);
insert into Productos (descripcion, stock, precio) values ('Apple - Delicious, Red', 46, 7413.36);
insert into Productos (descripcion, stock, precio) values ('Nantucket Cranberry Juice', 14, 3258.97);
insert into Productos (descripcion, stock, precio) values ('Cheese - Perron Cheddar', 98, 2804.58);
insert into Productos (descripcion, stock, precio) values ('Coffee Beans - Chocolate', 11, 8308.66);
insert into Productos (descripcion, stock, precio) values ('Ice Cream Bar - Oreo Sandwich', 53, 2151.87);
insert into Productos (descripcion, stock, precio) values ('Croissant, Raw - Mini', 15, 2105.22);
insert into Productos (descripcion, stock, precio) values ('Juice - V8, Tomato', 93, 9503.84);
insert into Productos (descripcion, stock, precio) values ('Pepper - Paprika, Hungarian', 21, 2451.54);
insert into Productos (descripcion, stock, precio) values ('Lobster - Baby, Boiled', 84, 2514.2);
insert into Productos (descripcion, stock, precio) values ('Tray - 12in Rnd Blk', 5, 9416.42);
insert into Productos (descripcion, stock, precio) values ('Cheese - Provolone', 20, 8970.12);
insert into Productos (descripcion, stock, precio) values ('Pate - Peppercorn', 94, 4188.99);
insert into Productos (descripcion, stock, precio) values ('Salmon - Smoked, Sliced', 73, 5093.23);
